services:
  # 1. INFRAESTRUTURA COMPARTILHADA (MENSAGERIA)

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - studyhub-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - studyhub-net

  # 2. CONTEXTO: Autenticação

  studyhub-auth-db:
    image: postgres:15-alpine
    container_name: studyhub-auth-db
    environment:
      POSTGRES_DB: studyhub_auth_db
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    ports:
      - "5432:5432" # Porta padrão
    networks:
      - studyhub-net

  studyhub-auth-service:
    build:
      context: ./studyhub-auth-service
    container_name: studyhub-auth-service
    ports:
      - "8081:8081"
    environment:
      - AUTH_DB_URL=jdbc:postgresql://studyhub-auth-db:5432/studyhub_auth_db
      - AUTH_DB_USER=${AUTH_DB_USER}
      - AUTH_DB_PASSWORD=${AUTH_DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - KAFKA_URL=kafka:9092
    depends_on:
      - studyhub-auth-db
      - kafka
    networks:
      - studyhub-net

  # 3. CONTEXTO: Chat

  studyhub-comm-db:
    image: postgres:15-alpine
    container_name: studyhub-comm-db
    environment:
      POSTGRES_DB: studyhub_communication_db
      POSTGRES_USER: ${COMMUNICATION_DB_USER}
      POSTGRES_PASSWORD: ${COMMUNICATION_DB_PASSWORD}
    ports:
      - "5433:5432" # Porta mapeada na máquina hospedeira para não conflitar com o DB do Auth
    networks:
      - studyhub-net

  studyhub-communication-service:
    build:
      context: ./studyhub-communication-service
    container_name: studyhub-communication-service
    ports:
      - "8085:8085"
    environment:
      - COMMUNICATION_DB_URL=jdbc:postgresql://studyhub-comm-db:5432/studyhub_communication_db
      - COMMUNICATION_DB_USER=${COMMUNICATION_DB_USER}
      - COMMUNICATION_DB_PASSWORD=${COMMUNICATION_DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - KAFKA_URL=kafka:9092
    depends_on:
      - studyhub-comm-db
      - kafka
    networks:
      - studyhub-net

  # 4. CONTEXTO: MONÓLITO (Salas e Guias)

  studyhub-monolith-db:
    image: postgres:15-alpine
    container_name: studyhub-monolith-db
    environment:
      POSTGRES_DB: studyhub_db
      POSTGRES_USER: ${MONOLITH_DB_USER}
      POSTGRES_PASSWORD: ${MONOLITH_DB_PASSWORD}
    ports:
      - "5434:5432" # Terceiro DB em porta diferente localmente
    networks:
      - studyhub-net

  studyhub-monolith:
    build:
      context: ./studyhub-api-monolith
    container_name: studyhub-monolith
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://studyhub-monolith-db:5432/studyhub_db
      - SPRING_DATASOURCE_USERNAME=${MONOLITH_DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${MONOLITH_DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - KAFKA_URL=kafka:9092
    depends_on:
      - studyhub-monolith-db
      - kafka
    networks:
      - studyhub-net

networks:
  studyhub-net:
    driver: bridge
