spring.application.name=studyhub-api

server.port=8080
server.servlet.context-path=/api/v1

# Configurações do Banco de Dados PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/studyhub}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Limites de Upload de Arquivos
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Segurança do Token JWT
api.security.token.secret=${JWT_SECRET}